"""splita — A/B test analysis that is correct by default, informative by design."""

__version__ = "0.1.0"

from splita._types import (
    AATestResult,
    BanditResult,
    BayesianResult,
    BayesianStoppingResult,
    BoundaryResult,
    ClusterResult,
    CorrectionResult,
    DiDResult,
    EffectTimeSeriesResult,
    EValueResult,
    EValueState,
    ExperimentResult,
    GSResult,
    HTEResult,
    InteractionResult,
    MetricSensitivityResult,
    NoveltyCurveResult,
    PowerSimulationResult,
    QuantileResult,
    SampleSizeResult,
    SRMResult,
    SurrogateResult,
    SwitchbackResult,
    SyntheticControlResult,
    TriggeredResult,
    VarianceEstimateResult,
    mSPRTResult,
    mSPRTState,
)
from splita.bandits import BayesianStopping, LinTS, LinUCB, ThompsonSampler
from splita.causal import (
    ClusterExperiment,
    DifferenceInDifferences,
    SurrogateEstimator,
    SwitchbackExperiment,
    SyntheticControl,
)
from splita.core import (
    BayesianExperiment,
    Experiment,
    HTEEstimator,
    InteractionTest,
    MultipleCorrection,
    PowerSimulation,
    QuantileExperiment,
    SampleSize,
    SRMCheck,
    TriggeredExperiment,
)
from splita.diagnostics import (
    AATest,
    EffectTimeSeries,
    MetricSensitivity,
    NoveltyCurve,
    VarianceEstimator,
)
from splita.governance import ConflictDetector, ConflictResult, ExperimentRegistry
from splita.sequential import EValue, GroupSequential, mSPRT
from splita.variance import CUPAC, CUPED, OutlierHandler

__all__ = [
    "CUPAC",
    "CUPED",
    "AATest",
    "AATestResult",
    "BanditResult",
    "BayesianExperiment",
    "BayesianResult",
    "BayesianStopping",
    "BayesianStoppingResult",
    "BoundaryResult",
    "ClusterExperiment",
    "ClusterResult",
    "ConflictDetector",
    "ConflictResult",
    "CorrectionResult",
    "DiDResult",
    "DifferenceInDifferences",
    "EValue",
    "EValueResult",
    "EValueState",
    "EffectTimeSeries",
    "EffectTimeSeriesResult",
    "Experiment",
    "ExperimentRegistry",
    "ExperimentResult",
    "GSResult",
    "GroupSequential",
    "HTEEstimator",
    "HTEResult",
    "InteractionResult",
    "InteractionTest",
    "LinTS",
    "LinUCB",
    "MetricSensitivity",
    "MetricSensitivityResult",
    "MultipleCorrection",
    "NoveltyCurve",
    "NoveltyCurveResult",
    "OutlierHandler",
    "PowerSimulation",
    "PowerSimulationResult",
    "QuantileExperiment",
    "QuantileResult",
    "SRMCheck",
    "SRMResult",
    "SampleSize",
    "SampleSizeResult",
    "SurrogateEstimator",
    "SurrogateResult",
    "SwitchbackExperiment",
    "SwitchbackResult",
    "SyntheticControl",
    "SyntheticControlResult",
    "ThompsonSampler",
    "TriggeredExperiment",
    "TriggeredResult",
    "VarianceEstimateResult",
    "VarianceEstimator",
    "mSPRT",
    "mSPRTResult",
    "mSPRTState",
]
